### ISSUE TITLE
Error: Error building site: POSTCSS: failed to transform "css/styles.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/

### ISSUE THREAD

**Issue by ioannakatsanou** [opera7133/Blonde#77]
Locally the website is working fine.
During deployment in Github pages I get this error.

I have ran both 
npm install -g postcss-cli
npm install -g autoprefixer
inside the folder. I have also created the package.json file and the postcss.config.js file.

Please see here:
https://github.com/ioannakatsanou/Test.git

**Comment by opera7133** [comment]
One possible solution is to add the command to the step as it is.
Like this:
```
- name: Setup Node.js
  uses: actions/setup-node@v2
  with:
    node-version: '14'
- name: Install dependencies
  run: |
    npm install -g postcss-cli
    npm install -g autoprefixer
```
If you still have problems, try enabling extended.

**Comment by opera7133** [comment]
The indentation is wrong.
If you fix it, it will look like this:
```
name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: Install dependencies
        run: |
          npm install -g postcss-cli
          npm install -g autoprefixer
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```
